apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-debug
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: seaweedfs-storage
---
apiVersion: v1
kind: Pod
metadata:
  name: csi-debug
spec:
  containers:
    - command: [watch, iostat]
      image: busybox
      imagePullPolicy: IfNotPresent
      name: busybox
      volumeMounts:
        - mountPath: /data
          name: data
      workingDir: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: csi-debug
